#!/usr/bin/env python3
# <<<name>>> — AI Robot entry point
# Generated by sky-kit  |  Run: python start.py

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from core.bot import Bot
from core.config import Config


async def main():
    config = Config()
    bot = Bot(config)
    await bot.start()


if __name__ == '__main__':
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print()
        print("Goodbye! See you next time.")
    except Exception as exc:
        print(f"Fatal error: {exc}")
        sys.exit(1)
